import { z } from 'zod';

export const FieldSchema = z.object({
  theme: z.enum(['light', 'dark']).optional().default('light').describe('Theme variation: light or dark.'),
  type: z
    .enum([
      'textfield',
      'textarea',
      'select',
      'checkbox',
      'radio',
      'hidden',
      'color',
      'date',
      'email',
      'file',
      'month',
      'number',
      'password',
      'range',
      'search',
      'tel',
      'time',
      'url',
      'week',
      'other',
    ])
    .optional()
    .default('textfield')
    .describe('Control type — selects which composed atom renders the field.'),
  title: z.string().optional().describe('Field title, rendered above the control (or as a legend for checkbox/radio groups).'),
  titleDisplay: z
    .enum(['visible', 'invisible', 'hidden'])
    .optional()
    .default('visible')
    .describe('How to display the title: visible, invisible (visually hidden but announced), or hidden entirely.'),
  titleSize: z
    .enum(['extra-small', 'small', 'regular', 'large', 'extra-large'])
    .optional()
    .default('regular')
    .describe('Title size.'),
  label: z
    .string()
    .optional()
    .describe(
      'Control label — only meaningful for a single (non-grouped) checkbox/radio, rendered beside the control rather than above it.',
    ),
  description: z.string().optional().describe('Description text, rendered via a composed ct-field-description.'),
  name: z.string().describe('DOM name — required. Shared across every rendered control, including grouped checkbox/radio options.'),
  value: z.string().optional().describe('DOM value, for the single (non-grouped) control case.'),
  id: z.string().optional().describe('DOM id. Auto-generated when omitted.'),
  isInvalid: z.boolean().optional().default(false).describe('Whether the control (and its group, if any) is in an invalid state.'),
  isDisabled: z.boolean().optional().default(false).describe('Whether the control (and its group, if any) is disabled.'),
  isRequired: z.boolean().optional().default(false).describe('Whether the control (and its group, if any) is required.'),
  requiredText: z.string().optional().describe('Text shown within the title/legend when isRequired is set.'),
  orientation: z
    .enum(['vertical', 'horizontal'])
    .optional()
    .default('vertical')
    .describe('Layout orientation: title above the control (vertical) or beside it (horizontal).'),
  isInline: z
    .boolean()
    .optional()
    .default(false)
    .describe('Whether a checkbox/radio option group lays its items out inline (horizontally) rather than stacked.'),
  placeholder: z.string().optional().describe('Placeholder text, for textfield/textarea/input-passthrough control types.'),
  isMultiple: z.boolean().optional().default(false).describe('Whether the composed ct-select allows multiple selections.'),
  checked: z
    .boolean()
    .optional()
    .default(false)
    .describe('Whether the single (non-grouped) checkbox/radio control starts checked.'),
  message: z
    .string()
    .optional()
    .describe(
      'Validation/status message content, rendered via a composed ct-field-message. Shown automatically (with a generic fallback) when isInvalid is set even if this is empty.',
    ),
  prefix: z.string().optional().describe('Trusted HTML rendered before the control. Callers must sanitize this HTML before passing it.'),
  suffix: z.string().optional().describe('Trusted HTML rendered after the control. Callers must sanitize this HTML before passing it.'),
  modifierClass: z.string().optional().describe('Additional custom CSS classes.'),
});

export type FieldProps = z.infer<typeof FieldSchema>;

export const FieldOptionSchema = z.object({
  label: z.string().describe("The option's visible label, rendered via the composed ct-checkbox/ct-radio's own label."),
  value: z.string().optional().describe("DOM value for this option's control."),
  id: z.string().optional().describe("DOM id for this option's control. Auto-generated by the parent ct-field when omitted."),
  checked: z.boolean().optional().default(false).describe('Whether this option starts checked/selected.'),
  disabled: z.boolean().optional().default(false).describe('Whether this option is disabled.'),
});

export type FieldOptionProps = z.infer<typeof FieldOptionSchema>;
