import { LitElement } from 'lit';
import { customElement, property } from 'lit/decorators.js';

/**
 * A single option of a `ct-field` whose `type` is `checkbox` or `radio` — one item of the
 * repeatable option group (upstream `field.twig`'s `control` array). Mirrors the same
 * "light-DOM data holder, no shadow root, no visible output of its own" shape as
 * `ct-select-option`/`ct-accordion-item`: the parent `ct-field` reads each child's
 * label/value/id/checked/disabled via `querySelectorAll` and renders a real `ct-checkbox`
 * or `ct-radio` from that data (sharing the parent's `name` so the group behaves as one
 * control set), rather than this element being displayed itself.
 *
 * Kept separate from `ct-select-option` (rather than reusing it) even though the two carry
 * near-identical data, since `ct-field`'s checkbox/radio branch also needs a per-item
 * `checked`/`disabled` pair that `ct-select-option` names differently (`selected`) for a
 * different underlying control.
 */
@customElement('ct-field-option')
export class CtFieldOption extends LitElement {
  /** The option's visible label, rendered via the composed ct-checkbox/ct-radio's own `label`. */
  @property({ type: String }) label = '';

  /** DOM `value` for this option's control. */
  @property({ type: String }) value = '';

  /** DOM `id` for this option's control. Auto-generated by the parent `ct-field` when omitted. */
  @property({ type: String }) id = '';

  /** Whether this option starts checked/selected. */
  @property({ type: Boolean }) checked = false;

  /** Whether this option is disabled. */
  @property({ type: Boolean }) disabled = false;

  createRenderRoot() {
    return this;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ct-field-option': CtFieldOption;
  }
}
