// Regenerates icon-registry.ts from the SVG source files in ../src/components/ui/icon/icons/.
// Run this after adding/removing/updating a CivicTheme icon SVG in that directory.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const iconsDir = path.resolve(__dirname, '../src/components/ui/icon/icons');
const outFile = path.resolve(__dirname, '../src/components/ui/icon/icon-registry.ts');

const files = fs.readdirSync(iconsDir).filter((f) => f.endsWith('.svg')).sort();

const names = files.map((f) => f.replace(/\.svg$/, ''));

const entries = files.map((file) => {
  const name = file.replace(/\.svg$/, '');
  const source = fs.readFileSync(path.join(iconsDir, file), 'utf8').trim();
  return `  '${name}': ${JSON.stringify(source)},`;
});

const output = `// Generated by scripts/build-icons.mjs from icons/*.svg — do not edit by hand.
// Source: https://github.com/civictheme/uikit/tree/main/packages/sdc/assets/icons

export const ICON_NAMES = [
${names.map((n) => `  '${n}',`).join('\n')}
] as const;

export type IconName = (typeof ICON_NAMES)[number];

export const ICON_SOURCES: Record<IconName, string> = {
${entries.join('\n')}
};
`;

fs.writeFileSync(outFile, output, 'utf8');
console.log(`Wrote ${names.length} icons to ${path.relative(process.cwd(), outFile)}`);
