import { LitElement, html, css, unsafeCSS } from "lit";
import { customElement, property } from "lit/decorators.js";
// Import the specific flattened constants generated by Style Dictionary
import { BreakpointM, BreakpointL, BreakpointXl } from "@ct-infra/tokens";

@customElement("ct-grid-item")
export class ctGridItem extends LitElement {
  /**
   * Column span for the smallest tier (xxs/xs)
   */
  @property({ type: Number }) span = 12;

  /**
   * Column span for medium (m) and large (l) tiers
   */
  @property({ type: Number }) spanM = 6;
  @property({ type: Number }) spanL = 6;

  /**
   * Column span for extra-large (xl) and above
   */
  @property({ type: Number }) spanXl = 4;

  static styles = css`
    :host {
      display: block;
      grid-column: span var(--grid-item-span, 12);
    }

    /* Use the constants directly without .$value */
    @media (min-width: ${unsafeCSS(BreakpointM)}) {
      :host {
        grid-column: span var(--grid-item-span-m, var(--grid-item-span));
      }
    }

    @media (min-width: ${unsafeCSS(BreakpointL)}) {
      :host {
        grid-column: span var(--grid-item-span-l, var(--grid-item-span-m));
      }
    }

    @media (min-width: ${unsafeCSS(BreakpointXl)}) {
      :host {
        grid-column: span var(--grid-item-span-xl, var(--grid-item-span-l));
      }
    }
  `;

  updated(changedProperties: Map<string, any>) {
    const props = ["span", "spanM", "spanL", "spanXl"];
    props.forEach((prop) => {
      if (changedProperties.has(prop)) {
        const cssSuffix = prop.replace(/[A-Z]/g, (m) => "-" + m.toLowerCase());
        this.style.setProperty(
          `--grid-item-${cssSuffix}`,
          (this as any)[prop].toString(),
        );
      }
    });
  }

  render() {
    return html`<slot></slot>`;
  }
}
